- name: Ensure sysctl is configured
  hosts: database
  become: true
  # gather_facts: no
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Install custom fact
      ansible.builtin.copy:
        content: |-
          [sample_exam]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact


    - name: Re-read facts after adding custom fact
      ansible.builtin.setup:
        filter: ansible_local
    - debug:
        var: ansible_local.custom.sample_exam 

      