- name: Ensure frontend is configured
  hosts: webservers
  become: true
  tasks:
  - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes