- name: Ensure server list
  hosts: database
  become: true
  tasks:
    - template:
        src: templates/server_list.j2
        dest: /etc/server_list.txt 
        owner: automation
        mode: 0600
        setype: net_conf_t
